### ISSUE TITLE
Unable to see this card in "Add card" menu

### ISSUE THREAD

**Issue by hiatsu0** [Sese-Schneider/ha-energy-overview-card#22]
Just installed version 2.2.0 through HACS on HA 2023.3.1 and for some reason the card does not appear in the "Add Card" menu in Lovelace. Tried even redownload in HACS and HA reboot but no, only other custom cards shown in the menu.

I can see the files are at `/config/www/community/ha-energy-overview-card` and it is listed in Dashboards > Resources (http://homeassistant/config/lovelace/resources) but even when adding some config code manually to a card it shows just an empty card. So somehow Lovelace is not loading this resource? No errors in logs (that I could find/associate to this)

![image](https://user-images.githubusercontent.com/66969014/223101372-c2cd35eb-7646-4be9-8f85-4014f26a172c.png)

**Comment by Sese-Schneider** [comment]
@hiatsu0 unfortunately currently, the card does not support being added through the "Add Card" menu.
Please add it manually via YAML config, the button is located on the very bottom in the manu.
You can have a look at an example here: https://github.com/Sese-Schneider/ha-energy-overview-card#example-configuration

However, I am currently working on a GUI editor, so that it can be used directly. I will ping you once its ready!

**Comment by hiatsu0** [comment]
Thanks for a quick reply! I tried the manual way as well (copying the example config and changing my sensors), that is what I tried to say with 

> when adding some config code manually to a card it shows just an empty card

But maybe I did something wrong, will try again!
